src/Entity/Post.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\PostRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private int $id;

    #[ORM\Column(type: 'string', length: 255)]
    private string $author;

    #[ORM\Column(type: 'string', length: 255)]
    private string $title;

    #[ORM\Column(type: 'string', length: 255)]
    private string $short_desc;

    #[ORM\Column(type: 'text')]
    private string $body;

    /**
     * @Assert\Image()
     *     minWidth = 200,
     *     maxWidth = 400,
     *     minHeight = 200,
     *     maxHeight = 400
     **/
    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private string $image;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\Column(type: 'datetime_immutable')]
    private DateTimeImmutable $createdAt;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getShortDesc(): ?string
    {
        return $this->short_desc;
    }

    public function setShortDesc(string $short_desc): self
    {
        $this->short_desc = $short_desc;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComment(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comments): self
    {
        if (!$this->comments->contains($comments)) {
            $this->comments[] = $comments;
            $comments->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comments): self
    {
        if ($this->comments->removeElement($comments)) {
            // set the owning side to null (unless already changed)
            if ($comments->getPost() === $this) {
                $comments->setPost(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function prePersist()
    {
        if (!$this->getCreatedAt()) {
            $this->setCreatedAt(new (date_create_immutable()));
        }
    }
}

src/Controller/BlogpressController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Post;
use App\Repository\CommentRepository;
use App\Repository\PostRepository;
use App\Entity\Comment;
use App\Form\Type\CommentFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BlogpressController extends AbstractController
{
    public function __construct(
        private readonly PostRepository $postRepository,
        private readonly CommentRepository $commentRepository
    )
    {
    }

    #[Route('/', name: 'app_blogpress')]
    public function index(): Response
    {
        return $this->render('blogpress/index.html.twig', [
            'posts' => $this->postRepository->findBy([], ['createdAt' => 'DESC']),
            'comments'=>$this->commentRepository->findAll(),
        ]);
    }

    #[Route(path: '/post/{id}', name: 'app_user_post_comment')]
    public function placeComment(Post $post, EntityManagerInterface $entityManager, Request $request): Response
    {
        $form = $this->createForm(CommentFormType::class, new Comment());
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $comment = $form->getData();
            $comment->setCreatedAt(date_create_immutable());
            $post->addComment($comment);
            $entityManager->persist($comment);
            $entityManager->flush();
            return $this->redirectToRoute('app_blogpress');
        }

        return $this->render('blogpress/showPost.html.twig', [
            'comment_form' => $form->createView()
        ]);
    }
}

templates/blogpress/admin/create.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <style>
        .align-center {
            margin: 0 auto;
        }
    </style>
{% endblock %}
{% block body %}
<div class="row">
    <div class="col-lg-8 align-center">
        <h1>Create new blog entry.</h1>
        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="flash-{{ label }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endfor %}
        {{ form_start(form) }}
        <div class="form-group">
           Title {{ form_widget(form.title) }}
        </div>
        <div class="form-group">
           Description {{ form_widget(form.shortDesc) }}
        </div>
        <div class="form-group">
          Image:  {{ form_widget(form.imageFile) }}
        </div>
        <div class="form-group">
         Post text:   {{ form_widget(form.body) }}
        </div>

        <input type="submit" class="btn btn-primary"/>

        {{ form_end(form) }}
    </div>
</div>
{% endblock %}

templates/blogpress/admin/index.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <style>
        .align-center {
            margin: 0 auto;
        }
    </style>
{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-lg-8 align-center">
            <h1>Posts</h1>
            <table class="table table-striped ">
                <thead class="thead-dark">

                <tr>
                    <th>Title</th>
                    <th>Short description</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for post in posts %}
                    <tr>
                        <td>{{ post.title }}</td>
                        <td>{{ post.shortDesc }}</td>
                        <td>
                            <a href="{{ path('app_admin_post_edit', {id: post.id}) }}" class="btn btn-primary">Edit</a>
                            <a href="{{ path('app_admin_post_delete', {id: post.id}) }}" onclick="return confirm('Are you sure?');" class="btn btn-danger">DELETE</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
    <div class="row">
        <div class="col-lg-8  align-center">
            <a href="{{ path('app_admin_post_create') }}" class="btn btn-primary">Create a post</a>
            <a href="{{ path('app_blogpress') }}" class="btn btn-secondary">Go to blog</a>
        </div>
    </div>

{% endblock %}